# fly.toml app configuration file generated for detectix-server on 2023-07-03T01:59:59+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "detectix-server"
primary_region = "sin"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
